### ISSUE TITLE
issues on x/twitter authentication

### ISSUE THREAD

**Issue by Mantodkaz** [volaradlp/minercli#16]
LOGS
[error] failed to update token at flow_duplication_check
'flow_token'
[error] xxxx login failed
Failed to authenticate X account xxxx.
Exiting...

**Comment by volaradao** [comment]
Hi, we recommend

1. Ensure that the email you use is the correct email associated with the X account
2. Ensure you do not have 2fa enabled.
3. Try to log in/log out on a browser

**Comment by akton0208** [comment]
i don't have 2fa enable but still got the same error

**Comment by PAKIDHO11** [comment]
Good

**Comment by Mantodkaz** [comment]
all good, i have update repo
